### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by mrsherobrine**
i said i would do it, so here it is :p

one thing to note: i translated Watchers as followers because Watcher doesnt translate well (it would mean viewer)

### CODE REVIEW

**Comment by mrsherobrine** [comment]
did a small dumb,: forgot to upload the file xd

**Comment by electronicboy** [comment]
> did a small dumb,;

The one.. the only...

**Comment by mrsherobrine** [comment]
idk where the language switcher code is so i'll leave that to the others ^^;

**Comment by mrsherobrine** [comment]
fixed :D

**Comment by MiniDigger** [comment]
thank you!
the language switcher will pick it up automagically

**Comment by MiniDigger** [comment]
well, that was a lie
what you forgot was importing thing file, theeeeenn it automagically shows up :D
https://github.com/PaperMC/Hangar/commit/a0cda24875c93c90d224bf4797deac9bba20e4e4

**Comment by mrsherobrine** [comment]
that's that, thanks :D

**Pull request merged**
