### PR TITLE
work on version selector

### LINKED ISSUE #97: Add supported version selector
Since the full range of supported versions can't be detected automatically and so that people don't have to put it into their docs manually, add checkboxes for version support in project settings and have a small display on the project's sidebar

### PR DESCRIPTION
**Pull request by Machine-Maker**
closes #97 

Not sure if adding to the Platform enum is the best way to have a list of possible versions, not sure of the best way to display the multiple version information. 

Still needs feedback

### CODE REVIEW

**Comment by KennyTV** [comment]
A dedicated config would be better, so that we won't have to recompile and deploy for just adding stuff

**Comment by Machine-Maker** [comment]
@KennyTV you mean like in the application.yml? or something that admins can edit?

**Comment by KennyTV** [comment]
I meant the application yml yeah, but I suppose a list in the db would probably be better for live updating (and having a simple admin page to add them?)

**Comment by Machine-Maker** [comment]
Yeah, ok. I like the db better. Can probably get away with 1 table for all of them.

**Comment by Machine-Maker** [comment]
k, this could use a bit of looking over from someone. Should be done tho. There was an unused permission, ManualValueChanges which seems appropriate for this. Not sure what its supposed to be for, it looks unused in Ore. HangarAdmin and HangarDev have it.

**Comment by MiniDigger** [comment]
definitely like the new table, I think in general all those hardcodes enums (roles, platforms) etc, should be defined by DB and then handled as constants in code, as thats just way easier to work with from the admin

**Comment by Machine-Maker** [comment]
Well I'm not sure *all* the hardcoded enums really need to have an admin manage page. For example, NamedPermission, that doesn't really needed to be managed on the frontend, since adding one of those always accompanies code changes. Im thinking
* Category
* Color
* FlagReason
* Platform
* Role
* TagColor

I think that is all that should be managed on the frontend.

**Comment by MiniDigger** [comment]
Agree

**Comment by Machine-Maker** [comment]
I think they each probably need their own db table right?

**Pull request merged**
