### PR TITLE
External url

### PR DESCRIPTION
**Pull request by Machine-Maker**
Ability to create versions with an external link.
Couple things still to do.

- [x] Redirect downloads to external URL
- [x] configurable list of URL hosts to avoid download warnings
- [x] external download warning dialog
- [x] api download links
- [ ] download counting

probably some more.

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Ok, this should be done.

The configurable list of "safe hosts" is in the application.yml. It can probably stay there. That isn't gonna change too often, or really at all once the initial list is set.

Basically, upon creating a version, you can either select a file, or input a URL. If its a URL, various fields are editable like the version name, the platform, and possible versions, etc.

**Comment by Machine-Maker** [comment]
Oh, there actually is one more thing. Download counts. How do we want to manage those for external downloads?

**Comment by KennyTV** [comment]
Exact same thing as for normal downloads :p

**Comment by Machine-Maker** [comment]
Ok, what should happen if someone navigates to download the jar for a version. We have the generic download links, but there is also download a jar specifically

Should those 404 or 400 or something? or redirect as well?

**Comment by Machine-Maker** [comment]
Ok, its easy enough to change that at a later date. Gonna merge this.

**Pull request merged**
